/*
Visier Document Search API

Visier API for searching for Visier documents

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SimpleDocumentHeaderSearchResultDTO } from './simple-document-header-search-result-dto';

/**
 * The response body structure for Simple document header search operations.
 * @export
 * @interface SimpleDocumentHeaderSearchResponseDTO
 */
export interface SimpleDocumentHeaderSearchResponseDTO {
    /**
     * The ordered collection of document header search results. The results are sorted according to their relevance in a descending order.
     * @type {Array<SimpleDocumentHeaderSearchResultDTO>}
     * @memberof SimpleDocumentHeaderSearchResponseDTO
     */
    'documentHeaders'?: Array<SimpleDocumentHeaderSearchResultDTO>;
}

