/*
Visier Document Search API

Visier API for searching for Visier documents

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The response structure for errors.
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * Error classification.
     * @type {string}
     * @memberof Status
     */
    'errorCode'?: string;
    /**
     * Error message describing the root cause of the error.
     * @type {string}
     * @memberof Status
     */
    'message'?: string;
}

